// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSettings() {
  return window['go']['main']['App']['CancelSettings']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function EnterSettingsMode() {
  return window['go']['main']['App']['EnterSettingsMode']();
}

export function ExitSettingsMode() {
  return window['go']['main']['App']['ExitSettingsMode']();
}

export function GetAppDataDir() {
  return window['go']['main']['App']['GetAppDataDir']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogDir() {
  return window['go']['main']['App']['GetLogDir']();
}

export function GetPinnedMessages() {
  return window['go']['main']['App']['GetPinnedMessages']();
}

export function GetTTSInfo() {
  return window['go']['main']['App']['GetTTSInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideOverlay() {
  return window['go']['main']['App']['HideOverlay']();
}

export function IsOverlay() {
  return window['go']['main']['App']['IsOverlay']();
}

export function OnChatMessage(arg1) {
  return window['go']['main']['App']['OnChatMessage'](arg1);
}

export function OnQueueUpdate(arg1) {
  return window['go']['main']['App']['OnQueueUpdate'](arg1);
}

export function OnSpeakFadeStart(arg1) {
  return window['go']['main']['App']['OnSpeakFadeStart'](arg1);
}

export function OnSpeakStart(arg1) {
  return window['go']['main']['App']['OnSpeakStart'](arg1);
}

export function OnTTSError(arg1, arg2) {
  return window['go']['main']['App']['OnTTSError'](arg1, arg2);
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function PassMessage() {
  return window['go']['main']['App']['PassMessage']();
}

export function PinLastMessage() {
  return window['go']['main']['App']['PinLastMessage']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RegisterHotkeys() {
  return window['go']['main']['App']['RegisterHotkeys']();
}

export function ReloadConfig(arg1) {
  return window['go']['main']['App']['ReloadConfig'](arg1);
}

export function ResizeWindow(arg1, arg2) {
  return window['go']['main']['App']['ResizeWindow'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveCurrentPosition() {
  return window['go']['main']['App']['SaveCurrentPosition']();
}

export function SavePosition(arg1, arg2) {
  return window['go']['main']['App']['SavePosition'](arg1, arg2);
}

export function ShowOverlay() {
  return window['go']['main']['App']['ShowOverlay']();
}

export function ToggleOverlay() {
  return window['go']['main']['App']['ToggleOverlay']();
}

export function ToggleVisibility() {
  return window['go']['main']['App']['ToggleVisibility']();
}

export function UnpinMessage() {
  return window['go']['main']['App']['UnpinMessage']();
}

export function UpdateHotkeys() {
  return window['go']['main']['App']['UpdateHotkeys']();
}
