// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {irc} from '../models';
import {main} from '../models';

export function CancelSettings():Promise<void>;

export function Connect(arg1:config.Config):Promise<void>;

export function Disconnect():Promise<void>;

export function EnterSettingsMode():Promise<void>;

export function ExitSettingsMode():Promise<void>;

export function GetAppDataDir():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetLogDir():Promise<string>;

export function GetPinnedMessages():Promise<Array<irc.ChatMessage>>;

export function GetTTSInfo():Promise<main.TTSInfo>;

export function Greet(arg1:string):Promise<string>;

export function HideOverlay():Promise<void>;

export function IsOverlay():Promise<boolean>;

export function OnChatMessage(arg1:any):Promise<void>;

export function OnQueueUpdate(arg1:Array<irc.ChatMessage>):Promise<void>;

export function OnSpeakFadeStart(arg1:irc.ChatMessage):Promise<void>;

export function OnSpeakStart(arg1:irc.ChatMessage):Promise<void>;

export function OpenSettings():Promise<void>;

export function PassMessage():Promise<void>;

export function PinLastMessage():Promise<void>;

export function Quit():Promise<void>;

export function RegisterHotkeys():Promise<void>;

export function ReloadConfig(arg1:config.Config):Promise<void>;

export function ResizeWindow(arg1:number,arg2:number):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveCurrentPosition():Promise<void>;

export function SavePosition(arg1:number,arg2:number):Promise<void>;

export function ShowOverlay():Promise<void>;

export function ToggleOverlay():Promise<void>;

export function ToggleVisibility():Promise<void>;

export function UnpinMessage():Promise<void>;

export function UpdateHotkeys():Promise<void>;
